# Static top-50 S&P 500 holdings by weight (approximate, as of early 2026).
# Used as fallback when slickcharts.com is unreachable (e.g. PythonAnywhere free tier).
# Update periodically by checking https://slickcharts.com/sp500

TOP_50 = [
    {"rank": 1,  "name": "Apple Inc.",                    "symbol": "AAPL",  "weight": 6.82},
    {"rank": 2,  "name": "NVIDIA Corporation",            "symbol": "NVDA",  "weight": 6.51},
    {"rank": 3,  "name": "Microsoft Corporation",         "symbol": "MSFT",  "weight": 6.20},
    {"rank": 4,  "name": "Amazon.com Inc.",               "symbol": "AMZN",  "weight": 3.98},
    {"rank": 5,  "name": "Meta Platforms Inc.",           "symbol": "META",  "weight": 2.78},
    {"rank": 6,  "name": "Alphabet Inc. (Class A)",       "symbol": "GOOGL", "weight": 2.00},
    {"rank": 7,  "name": "Alphabet Inc. (Class C)",       "symbol": "GOOG",  "weight": 1.72},
    {"rank": 8,  "name": "Berkshire Hathaway Inc.",       "symbol": "BRK-B", "weight": 1.67},
    {"rank": 9,  "name": "Broadcom Inc.",                 "symbol": "AVGO",  "weight": 1.64},
    {"rank": 10, "name": "Tesla Inc.",                    "symbol": "TSLA",  "weight": 1.55},
    {"rank": 11, "name": "Eli Lilly and Company",         "symbol": "LLY",   "weight": 1.33},
    {"rank": 12, "name": "JPMorgan Chase & Co.",          "symbol": "JPM",   "weight": 1.32},
    {"rank": 13, "name": "Visa Inc.",                     "symbol": "V",     "weight": 1.04},
    {"rank": 14, "name": "UnitedHealth Group Inc.",       "symbol": "UNH",   "weight": 0.97},
    {"rank": 15, "name": "Exxon Mobil Corporation",       "symbol": "XOM",   "weight": 0.95},
    {"rank": 16, "name": "Mastercard Incorporated",       "symbol": "MA",    "weight": 0.93},
    {"rank": 17, "name": "Costco Wholesale Corporation",  "symbol": "COST",  "weight": 0.87},
    {"rank": 18, "name": "Johnson & Johnson",             "symbol": "JNJ",   "weight": 0.84},
    {"rank": 19, "name": "Walmart Inc.",                  "symbol": "WMT",   "weight": 0.81},
    {"rank": 20, "name": "Procter & Gamble Co.",          "symbol": "PG",    "weight": 0.78},
    {"rank": 21, "name": "Oracle Corporation",            "symbol": "ORCL",  "weight": 0.77},
    {"rank": 22, "name": "Home Depot Inc.",               "symbol": "HD",    "weight": 0.74},
    {"rank": 23, "name": "Netflix Inc.",                  "symbol": "NFLX",  "weight": 0.72},
    {"rank": 24, "name": "Advanced Micro Devices Inc.",   "symbol": "AMD",   "weight": 0.66},
    {"rank": 25, "name": "Salesforce Inc.",               "symbol": "CRM",   "weight": 0.65},
    {"rank": 26, "name": "Bank of America Corp.",         "symbol": "BAC",   "weight": 0.64},
    {"rank": 27, "name": "Adobe Inc.",                    "symbol": "ADBE",  "weight": 0.63},
    {"rank": 28, "name": "Accenture plc",                 "symbol": "ACN",   "weight": 0.60},
    {"rank": 29, "name": "Chevron Corporation",           "symbol": "CVX",   "weight": 0.59},
    {"rank": 30, "name": "Wells Fargo & Company",         "symbol": "WFC",   "weight": 0.57},
    {"rank": 31, "name": "Cisco Systems Inc.",            "symbol": "CSCO",  "weight": 0.55},
    {"rank": 32, "name": "ASML Holding N.V.",             "symbol": "ASML",  "weight": 0.54},
    {"rank": 33, "name": "Pepsico Inc.",                  "symbol": "PEP",   "weight": 0.52},
    {"rank": 34, "name": "QUALCOMM Incorporated",         "symbol": "QCOM",  "weight": 0.51},
    {"rank": 35, "name": "Abbott Laboratories",           "symbol": "ABT",   "weight": 0.50},
    {"rank": 36, "name": "T-Mobile US Inc.",              "symbol": "TMUS",  "weight": 0.49},
    {"rank": 37, "name": "Intuitive Surgical Inc.",       "symbol": "ISRG",  "weight": 0.48},
    {"rank": 38, "name": "International Business Machines","symbol": "IBM",  "weight": 0.47},
    {"rank": 39, "name": "Goldman Sachs Group Inc.",      "symbol": "GS",    "weight": 0.46},
    {"rank": 40, "name": "Linde plc",                    "symbol": "LIN",   "weight": 0.45},
    {"rank": 41, "name": "Caterpillar Inc.",              "symbol": "CAT",   "weight": 0.44},
    {"rank": 42, "name": "Amgen Inc.",                    "symbol": "AMGN",  "weight": 0.43},
    {"rank": 43, "name": "Thermo Fisher Scientific Inc.", "symbol": "TMO",   "weight": 0.42},
    {"rank": 44, "name": "Morgan Stanley",                "symbol": "MS",    "weight": 0.41},
    {"rank": 45, "name": "RTX Corporation",               "symbol": "RTX",   "weight": 0.40},
    {"rank": 46, "name": "Applied Materials Inc.",        "symbol": "AMAT",  "weight": 0.39},
    {"rank": 47, "name": "Booking Holdings Inc.",         "symbol": "BKNG",  "weight": 0.38},
    {"rank": 48, "name": "Charles Schwab Corporation",    "symbol": "SCHW",  "weight": 0.37},
    {"rank": 49, "name": "Danaher Corporation",           "symbol": "DHR",   "weight": 0.36},
    {"rank": 50, "name": "Blackrock Inc.",                "symbol": "BLK",   "weight": 0.35},
]
